// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBKZNAWHp22nBphPK7CYbuR9jCzDxeMAc',
    appId: '1:566918418345:web:777123e5f1da9f6acdbeb8',
    messagingSenderId: '566918418345',
    projectId: 'whats-up-d89cd',
    authDomain: 'whats-up-d89cd.firebaseapp.com',
    storageBucket: 'whats-up-d89cd.appspot.com',
    measurementId: 'G-6ZX9LQKSJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KWl4iDnOA3aOEKy4Cs5OAQh80kCIRN0',
    appId: '1:566918418345:android:1e7340aca3915da1cdbeb8',
    messagingSenderId: '566918418345',
    projectId: 'whats-up-d89cd',
    storageBucket: 'whats-up-d89cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFPFjIR0HTn9Co5Vmjaa_FBxgUU-S_UGk',
    appId: '1:566918418345:ios:1a69976217e86a6dcdbeb8',
    messagingSenderId: '566918418345',
    projectId: 'whats-up-d89cd',
    storageBucket: 'whats-up-d89cd.appspot.com',
    iosClientId: '566918418345-ttum28g5lgn1g453hqorjc99uenu6uo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
